- name: install the latest version of Apache
  yum:
    name: httpd
    state: latest

- name: check installation
  shell: rpm -qa --last | grep httpd
  register: pkg

- debug:
    msg: "{{pkg.stdout}}"